# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='sup_level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
