# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_userp_sup_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NominaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idacerh', models.CharField(blank=True, max_length=99999999)),
                ('idnomina', models.CharField(blank=True, max_length=99999999)),
                ('numero_nomina', models.CharField(blank=True, max_length=99999999)),
                ('periodo', models.CharField(blank=True, max_length=10)),
                ('concepto1', models.CharField(blank=True, max_length=50)),
                ('concepto2', models.CharField(blank=True, max_length=50)),
                ('concepto3', models.CharField(blank=True, max_length=50)),
                ('concepto4', models.CharField(blank=True, max_length=50)),
                ('concepto5', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userp',
            name='ingreso',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userp',
            name='area',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Area'),
            preserve_default=False,
        ),
    ]
