# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userp_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Area'),
            preserve_default=False,
        ),
    ]
