# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180729_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area2',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area2',
        ),
    ]
