# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('h115', models.CharField(blank=True, max_length=20)),
                ('h135', models.CharField(blank=True, max_length=20)),
                ('h_descuento', models.CharField(blank=True, max_length=20)),
                ('feriado', models.CharField(blank=True, max_length=20)),
                ('inventivos', models.CharField(blank=True, max_length=20)),
                ('comisiones', models.CharField(blank=True, max_length=20)),
                ('ausencias', models.CharField(blank=True, max_length=20)),
                ('descuento_hora', models.CharField(blank=True, max_length=20)),
                ('descuento_almuerzo', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userp',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Area'),
            preserve_default=False,
        ),
    ]
