# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-18 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180729_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userp',
            name='area',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='ingreso',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='sup_level',
        ),
        migrations.AlterField(
            model_name='novedades',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
