# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ncf.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalleg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('rnc', models.CharField(blank=True, max_length=20)),
                ('ncf', models.CharField(blank=True, max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('itbis', models.DecimalField(decimal_places=2, max_digits=999999)),
                ('fecha', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=999999)),
                ('total', models.DecimalField(decimal_places=2, max_digits=999999)),
                ('estatus', models.CharField(blank=True, max_length=20)),
                ('file', models.FileField(blank=True, upload_to=ncf.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=999999)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('moneda', models.CharField(blank=True, max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_final', models.DecimalField(decimal_places=2, max_digits=999999)),
                ('nota', models.TextField(blank=True)),
                ('estatus', models.CharField(blank=True, max_length=20)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detalleg',
            name='gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncf.Gasto'),
        ),
    ]
