# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncf', '0002_auto_20180225_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleg',
            name='proveedor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
