# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncf', '0003_detalleg_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='estatus',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
