# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncf', '0007_auto_20180321_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleg',
            name='estatus',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
