# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncf', '0008_detalleg_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleg',
            name='fecha',
            field=models.TextField(blank=True, max_length=12),
        ),
    ]
