# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncf', '0004_gasto_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleg',
            name='gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncf.Gasto'),
        ),
    ]
