# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncf', '0005_auto_20180225_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleg',
            name='fecha',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
