# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncf', '0006_detalleg_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleg',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detalleg',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
