# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-17 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncf', '0009_auto_20180325_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleg',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
