# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-23 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncf', '0011_auto_20180417_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleg',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
